language: r
latex: true
pandoc: false
sudo: true
cache:
- packages
- "/tmp/texlive"
- "/$HOME/.texlive"
warnings_are_errors: false
before_install:
- source ./travis/texlive.sh
- sudo apt-get install ghostscript
- tlmgr install helvetic eurosym xstring csquotes logreq url eso-pic geometry hyperref
  psnfss colortbl acronym bigfoot blindtext chngcntr cmap nowidow mdframed navigator
  needspace tablefootnote tocloft xpatch multirow bbding mathastext isomath relsize
  koma-script carlisle cleveref enumitem footmisc microtype caption booktabs xifthen
  ifmtarg float adjustbox collectbox l3kernel appendix xkeyval placeins babel-english
install: echo Installation step
before_script:
- wget http://mirrors.ctan.org/biblio/biber/binaries/Linux/biber-linux_x86_64.tar.gz
- tar xzf biber-linux_x86_64.tar.gz
- export PATH=$PATH:$PWD
- tlmgr install dpfloat
- tlmgr update biber
- tlmgr update --all
- Rscript -e 'if (!requireNamespace("hunspell", quietly = TRUE)) system("sudo apt-get
  install -y r-cran-devtools r-cran-rcpp r-cran-bh r-cran-stringi r-cran-hunspell")'
- Rscript -e 'install.packages("hutils", quiet = TRUE)'
- Rscript -e 'devtools::install_github("hughparsonage/TeXCheckR", quiet = TRUE)'
- Rscript -e 'devtools::install_github("hughparsonage/grattanReporter", quiet = TRUE)'
script:
- tlmgr --version
- set -e
- touch INCLUDEALL.txt
- Rscript -e 'tools::find_gs_cmd()'
- Rscript -e 'library(grattanReporter);options("check.CenturyFootnote" = FALSE);Sys.setenv(R_GSCMD
  = tools::find_gs_cmd());checkGrattanReport(compile = TRUE, pre_release= TRUE, release
  = TRUE, .proceed_after_rerun = 4)'
- Rscript -e 'file.copy(dir(path = "RELEASE", pattern = ".pdf$", full.names = TRUE)[1],
  "Report.pdf", overwrite = TRUE)'
notifications:
  slack: grattex:7yiVyM6NvMmCE49ccxaUX2QG#aust-perspectives
  on_success: change
branches:
  only: master

before_deploy:
   # Set up git user name and tag this commit
      - git config --local user.name "HughParsonage"
      - git config --local user.email "hugh.parsonage@gmail.com"
      - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: BcOdse+cwiTuNGEFySRZVMgXYYKVgkPRrRuThtlle+e4x/h3UJ1rm+dIl7I6bRp75dKf6DEhREjBxdZ13gTqMMM44rSdg0HWDKjwV0A+WKqSwRNKw8R88UIfZ+BuHp6EPv97N7JNSQnTXQXbqHG7LrfRSlVGsfad1U158zxqZUF7iCWF6GAkrZWT+uzU/fAuiNRJlOdLI9ukbRFLkchZSy5KknpKWqvjjceZxrrtELFqUT2qaL+klr17YA5F4vDJRT6Q9/hdVMqKaNVIXDqLgvtDwrOspfKEqvJxKjIovjM7yDfF6zFKHCZ2yErHmzd1OPdGyXyKHbu2lJZRGx9I05PfxH07eVXMNEgCOkye5B9aOuWDtvQvx91FrRysw2P290vZOPHYoKnyQaZkZHBKhClr+KPvM6427FfnnWpbvmPXZV3/dEW9XNbIOh1ghr7YZaosJ89q6N7adV1G/brxsE3Rv7RD002Yo6xsieHXiCPd9cuvHWlZOh6LKy4ZYc/3Uv4pR9VtKlgBnKtra+tPtUWXnloaaYKITD9BcdFF1gato1iqMkKkd9uQ+zmRTpsYENtmBy+IMdFpt+ExSGQuvVkKW8sY8M+FzjoJHR1CLV7327eSlT20TzE26PEDbyXMaLH+UvTx5IR/d8Al3tk0m9QhcG9zfAP6K8iFc4Ig1/w=
  file: Report.pdf
  on:
    repo: grattan/zzz-2018-Housing-affordability
