version: 2
jobs:
  build:
    working_directory: ~/main
    docker:
      - image: sumdoc/texlive-2018
        environment:
          NOT_CRAN: true
    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       - deps1-{{ .Branch }}
      #       - deps1-
      - run:
          command: |
            for i in *.tex; do pdflatex -halt-on-error -interaction=nonstopmode $i; done
            biber 'Report'
            for i in *.tex; do pdflatex -halt-on-error -interaction=batchmode $i; done
            for i in *.tex; do pdflatex -halt-on-error -interaction=batchmode $i; done
      # - run:
      #     command: |
      #       Rscript -e 'devtools::install_github("hughparsonage/hutils", keep_source = FALSE, quick = TRUE)'
      #       Rscript -e 'devtools::install_github("hughparsonage/TeXCheckR", keep_source = FALSE, quick = TRUE)'
      #       Rscript -e 'devtools::install_github("hughparsonage/grattanReporter", ref = "tinytex-compatible", keep_source = FALSE, quick = TRUE)'
      # - run:
      #     command: |
      #       Rscript -e 'devtools::install_github("yihui/tinytex", keep_source = FALSE, quick=TRUE)'
      #       Rscript -e 'library(tinytex);tlmgr_install(c("dpfloat", "ifmtarg", "ms", "pgf", "eso-pic", "babel-english", "eurosym", "koma-script", "footmisc", "xifthen", "xcolor", "adjustbox", "collectbox", "float", "placeins", "enumitem", "colortbl", "cleveref", "csquotes", "dvips", "blindtext", "cmap", "nowidow", "mdframed", "needspace", "tablefootnote", "tocloft", "xpatch", "multirow", "bbding", "biblatex", "logreq", "xstring", "biber", "mathastext", "isomath", "relsize"));tlmgr_update()'
      #       Rscript -e 'hutils::provide.dir("travis/grattanReport")'
      #       Rscript -e 'library(grattanReporter);checkGrattanReport(compile = TRUE, pre_release = TRUE)'
      # - save_cache:
      #     key: deps1-{{ .Branch }}-{{ checksum "grattan.cls" }} 
      #     paths:
      #       - "/root/.TinyTeX"
